Repository termcolor/termcolor, pull requests merged in 2022-09, with the labels that each got.

#17 Migrate from setuptools + setuptools_scm to hatchling + hatch-vcs
  .flake8
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: changelog: Changed

#18 Remove hardcoded VERSION constant
  src/termcolor/__init__.py
  src/termcolor/termcolor.py
Labels: changelog: Removed

#19 Autodeploy to TestPyPI and to PyPI for GH releases
  .github/workflows/deploy.yml
  RELEASING.md
Labels: changelog: Changed, release

#20 Refer to GitHub Releases for release notes for 2.0.0+
  CHANGES.md
Labels: changelog: Changed, release

#21 Update source URL
  pyproject.toml
Labels: bug, changelog: Fixed

#22 Add Tidelift
  .github/FUNDING.yml
  .github/SECURITY.md
  .github/labels.yml
  README.md
Labels: documentation, changelog: skip

#23 Deprecate `__ALL__`, use `__all__` instead
  src/termcolor/__init__.py
  src/termcolor/termcolor.py
  tests/test_termcolor.py
Labels: changelog: Deprecated
