Repository termcolor/termcolor, pull requests merged in 2025-04, with the labels that each got.

#100 Fix licence filename in metadata
  pyproject.toml
Labels: changelog: Fixed

#102 Add true colour RGB option as input arguments
  README.md
  src/termcolor/__main__.py
  src/termcolor/termcolor.py
  tests/test_termcolor.py
Labels: changelog: Added

#104 Advertise typing via classifier
  pyproject.toml
Labels: changelog: Added

#105 Migrate coverage configuration to pyproject.toml
  .coveragerc
  pyproject.toml
Labels: changelog: Changed

#106 Complete coverage via added tests
  pyproject.toml
  tests/test_termcolor.py
  tox.ini
Labels: changelog: skip

#107 Cache system lookups to save invocation time
  src/termcolor/termcolor.py
  tests/test_termcolor.py
Labels: changelog: Added

#108 Test code branches
  pyproject.toml
  tests/test_termcolor.py
Labels: changelog: skip

#109 Add mutation testing
  .gitignore
  tests/test_termcolor.py
  tox.ini
Labels: changelog: skip
